package org.tangsi.user.dao.mapper;

import org.tangsi.user.entity.User;

import java.util.List;
import java.util.Map;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Tue Jul 07 15:02:42 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Tue Jul 07 15:02:42 CST 2015
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Tue Jul 07 15:02:42 CST 2015
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Tue Jul 07 15:02:42 CST 2015
     */
    User selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Tue Jul 07 15:02:42 CST 2015
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Tue Jul 07 15:02:42 CST 2015
     */
    int updateByPrimaryKey(User record);

    /**
     * 查询用户及其关联的订单
     * @param id
     * @return
     */
    public User getUserWithOrdersByPrimaryKey(long id);

    /**
     * 批量插入数据，并返回插入的条数
     * @param users
     * @return
     */
    public int insertBatch(List<User> users);


    public List<User> selectAll();


    /**
     * 根据变量名来指定查询表名，与查询条件，注意$ # 两者的区别$只能替代表名，#只能替代字段名
     * @param paramMap
     * @return
     */
    public User selectWithParamMap(Map<String, Object> paramMap);

    public List<User> getUserWithBlogAndComment();
}