package org.tangsi.user.entity;

import org.hibernate.validator.constraints.Email;
import org.tangsi.blog.entity.Blog;
import org.tangsi.order.entity.Order;
import org.tangsi.user.validate.Login;
import org.tangsi.user.validate.Registe;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Pattern;
import java.util.List;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.id
     *
     * @mbggenerated Tue Jul 07 15:02:42 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.name
     *
     * @mbggenerated Tue Jul 07 15:02:42 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.email
     *
     * @mbggenerated Tue Jul 07 15:02:42 CST 2015
     * 采用jsr 303 注解式校验
     */
    @NotNull(message = "{email_not_null}", groups = {Login.class, Registe.class})  //分组验证：邮箱在登录与注册时都需要验证
    @Email(message = "{not_valid_email}", groups = {Login.class, Registe.class})
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.phone
     *
     * @mbggenerated Tue Jul 07 15:02:42 CST 2015
     */
    private String phone;

    /**
     * 用户名,
     */
    private String username;

    /**
     * 密码
     */
    @NotNull(message = "{password_not_null}", groups = {Login.class,Registe.class})
    @Pattern(regexp = "^(([a-zA-Z]+[\\d]+)+)|(([\\d]+)+[a-zA-Z]+)$", message = "{pwd_word_number}", groups = {Login.class,Registe.class})
    private String password;

    /**
     * 确认密码，用于用户注册时的校验
     */
    @NotNull(message = "{password_not_null}", groups = Registe.class)
    @Pattern(regexp = "^(([a-zA-Z]+[\\d]+)+)|(([\\d]+)+[a-zA-Z]+)$", message = "{confirm_pwd_word_number}", groups = Registe.class)
    private String confirmPassword;


    public String getConfirmPassword() {
        return confirmPassword;
    }

    public void setConfirmPassword(String confirmPassword) {
        this.confirmPassword = confirmPassword;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * 用户关联的订单
     */
    private List<Order> orders;

    private List<Blog> blogs;

    public List<Blog> getBlogs() {
        return blogs;
    }

    public void setBlogs(List<Blog> blogs) {
        this.blogs = blogs;
    }

    public List<Order> getOrders() {
        return orders;
    }

    public void setOrders(List<Order> orders) {
        this.orders = orders;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.id
     *
     * @return the value of t_user.id
     * @mbggenerated Tue Jul 07 15:02:42 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.id
     *
     * @param id the value for t_user.id
     * @mbggenerated Tue Jul 07 15:02:42 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.name
     *
     * @return the value of t_user.name
     * @mbggenerated Tue Jul 07 15:02:42 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.name
     *
     * @param name the value for t_user.name
     * @mbggenerated Tue Jul 07 15:02:42 CST 2015
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.email
     *
     * @return the value of t_user.email
     * @mbggenerated Tue Jul 07 15:02:42 CST 2015
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.email
     *
     * @param email the value for t_user.email
     * @mbggenerated Tue Jul 07 15:02:42 CST 2015
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.phone
     *
     * @return the value of t_user.phone
     * @mbggenerated Tue Jul 07 15:02:42 CST 2015
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.phone
     *
     * @param phone the value for t_user.phone
     * @mbggenerated Tue Jul 07 15:02:42 CST 2015
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }
}