package org.tangsi.order.entity;

public class Order {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.id
     *
     * @mbggenerated Tue Jul 07 15:02:42 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.createtime
     *
     * @mbggenerated Tue Jul 07 15:02:42 CST 2015
     */
    private Long createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.userId
     *
     * @mbggenerated Tue Jul 07 15:02:42 CST 2015
     */
    private Long userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.name
     *
     * @mbggenerated Tue Jul 07 15:02:42 CST 2015
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.id
     *
     * @return the value of t_order.id
     *
     * @mbggenerated Tue Jul 07 15:02:42 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.id
     *
     * @param id the value for t_order.id
     *
     * @mbggenerated Tue Jul 07 15:02:42 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.createtime
     *
     * @return the value of t_order.createtime
     *
     * @mbggenerated Tue Jul 07 15:02:42 CST 2015
     */
    public Long getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.createtime
     *
     * @param createtime the value for t_order.createtime
     *
     * @mbggenerated Tue Jul 07 15:02:42 CST 2015
     */
    public void setCreatetime(Long createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.userId
     *
     * @return the value of t_order.userId
     *
     * @mbggenerated Tue Jul 07 15:02:42 CST 2015
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.userId
     *
     * @param userid the value for t_order.userId
     *
     * @mbggenerated Tue Jul 07 15:02:42 CST 2015
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.name
     *
     * @return the value of t_order.name
     *
     * @mbggenerated Tue Jul 07 15:02:42 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.name
     *
     * @param name the value for t_order.name
     *
     * @mbggenerated Tue Jul 07 15:02:42 CST 2015
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}